### ISSUE TITLE
AttributeError: 'Column' object has no attribute 'sort'

### ISSUE THREAD

**Issue by Murhaf** [huggingface/setfit#608]
The [latest release of datasets](https://github.com/huggingface/datasets/releases/tag/4.0.0) introduces an `IterableColumn` object (in IterableDataset); therefore, setfit won't work with datasets 4.0.0 as `samples` is no longer a list in [`set_widget_examples` in `model_card.py`](https://github.com/huggingface/setfit/blob/main/src/setfit/model_card.py#L301)

```python
    def set_widget_examples(self, dataset: Dataset) -> None:
        samples = dataset.select(random.sample(range(len(dataset)), k=min(len(dataset), 5)))["text"]
        self.widget = [{"text": sample} for sample in samples]

        samples.sort(key=len)
        if samples:
            self.predict_example = samples[0]
```
